import type { NextPage } from "next";
import Head from "next/head";
import MainLayout from "../layouts/MainLayout";
import styles from "../styles/Home.module.scss";
import { Button } from "@mui/material";
import { useRouter } from "next/router";
import News from "../components/News";
import { INews } from "../types/news";

interface NewsProps {
  category: number;
  total: number;
  page: number;
  per_page: number;
  last_page: number;
  news: INews[];
}

const Home: React.FC<NewsProps> = ({ news }) => {
  const router = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>ITMO news</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <MainLayout>
          <News news={news} />
        </MainLayout>
      </main>
    </div>
  );
};

export default Home;

export async function getStaticProps(): Promise<{
  props: {
    news: INews[];
  };
}> {
  const response = await fetch(
    `https://news.itmo.ru/api/news/list/?ver=2.0&language_id=1&per_page=9&lead=true`
  );
  const data = await response.json();
  return {
    props: data,
  };
}
